var tasks = [
{"startDate":new Date("1969"),"endDate":new Date("1972"),"taskName":"Robson, B.T.","status":"CHAIR"},
{"startDate":new Date("1969"),"endDate":new Date("1970"),"taskName":"Garner, B.J.","status":"SEC"},
{"startDate":new Date("1969"),"endDate":new Date("1970"),"taskName":"Cowies, S.R.","status":"MEMBER"},
{"startDate":new Date("1969"),"endDate":new Date("1970"),"taskName":"Goddard, J.B.","status":"MEMBER"},
{"startDate":new Date("1970"),"endDate":new Date("1972"),"taskName":"Goddard, J.B.","status":"SEC"},
{"startDate":new Date("1972"),"endDate":new Date("1973"),"taskName":"Goddard, J.B.","status":"CHAIR"},
{"startDate":new Date("1973"),"endDate":new Date("1974"),"taskName":"Goddard, J.B.","status":"SEC"},
{"startDate":new Date("1969"),"endDate":new Date("1971"),"taskName":"Lewis, P.W.","status":"MEMBER"},
{"startDate":new Date("1970"),"endDate":new Date("1973"),"taskName":"Cliff, A.","status":"MEMBER"},
{"startDate":new Date("1970"),"endDate":new Date("1973"),"taskName":"Evans, I.S.","status":"MEMBER"},
{"startDate":new Date("1985"),"endDate":new Date("1987"),"taskName":"Evans, I.S.","status":"MEMBER"},
{"startDate":new Date("1971"),"endDate":new Date("1974"),"taskName":"Wilson, A.","status":"MEMBER"},
{"startDate":new Date("1972"),"endDate":new Date("1973"),"taskName":"Taylor, P.","status":"SEC"},
{"startDate":new Date("1973"),"endDate":new Date("1974"),"taskName":"Taylor, P.","status":"CHAIR"},
{"startDate":new Date("1974"),"endDate":new Date("1976"),"taskName":"Taylor, P.","status":"SEC"},
{"startDate":new Date("1976"),"endDate":new Date("1979"),"taskName":"Taylor, P.","status":"CATMOG"},
{"startDate":new Date("1972"),"endDate":new Date("1975"),"taskName":"Collins, L.","status":"MEMBER"},
{"startDate":new Date("1972"),"endDate":new Date("1975"),"taskName":"Hepple, L.","status":"MEMBER"},
{"startDate":new Date("1973"),"endDate":new Date("1976"),"taskName":"Clark,D.","status":"MEMBER"},
{"startDate":new Date("1973"),"endDate":new Date("1974"),"taskName":"Unwin,D.","status":"MEMBER"},
{"startDate":new Date("1974"),"endDate":new Date("1976"),"taskName":"Unwin,D.","status":"CHAIR"},
{"startDate":new Date("1976"),"endDate":new Date("1979"),"taskName":"Unwin,D.","status":"SEC"},
{"startDate":new Date("1981"),"endDate":new Date("1983"),"taskName":"Unwin,D.","status":"CATMOG"},
{"startDate":new Date("1974"),"endDate":new Date("1977"),"taskName":"Morgan, R.","status":"MEMBER"},
{"startDate":new Date("1974"),"endDate":new Date("1977"),"taskName":"Openshaw, S.","status":"MEMBER"},
{"startDate":new Date("1975"),"endDate":new Date("1978"),"taskName":"Dawson, A.","status":"MEMBER"},
{"startDate":new Date("1975"),"endDate":new Date("1977"),"taskName":"Johnston, R.","status":"MEMBER"},
{"startDate":new Date("1979"),"endDate":new Date("1981"),"taskName":"Johnston, R.","status":"CATMOG"},
{"startDate":new Date("1976"),"endDate":new Date("1979"),"taskName":"Wrigley, N.","status":"MEMBER"},
{"startDate":new Date("1979"),"endDate":new Date("1982"),"taskName":"Wrigley, N.","status":"SEC"},
{"startDate":new Date("1976"),"endDate":new Date("1979"),"taskName":"Thrift, N.","status":"MEMBER"},
{"startDate":new Date("1977"),"endDate":new Date("1979"),"taskName":"Bennett, R.","status":"MEMBER"},
{"startDate":new Date("1979"),"endDate":new Date("1982"),"taskName":"Bennett, R.","status":"CHAIR"},
{"startDate":new Date("1982"),"endDate":new Date("1985"),"taskName":"Bennett, R.","status":"SEC"},
{"startDate":new Date("1977"),"endDate":new Date("1980"),"taskName":"Ferguson,R.I.","status":"MEMBER"},
{"startDate":new Date("1978"),"endDate":new Date("1981"),"taskName":"Bradford, M.","status":"MEMBER"},
{"startDate":new Date("1978"),"endDate":new Date("1980"),"taskName":"Harris, R.","status":"MEMBER"},
{"startDate":new Date("1979"),"endDate":new Date("1982"),"taskName":"Cox, N.J.","status":"MEMBER"},
{"startDate":new Date("1979"),"endDate":new Date("1982"),"taskName":"Gattrell, A.C.","status":"MEMBER"},
{"startDate":new Date("1983"),"endDate":new Date("1987"),"taskName":"Gattrell, A.C.","status":"CATMOG"},
{"startDate":new Date("1981"),"endDate":new Date("1983"),"taskName":"Silk, J.","status":"MEMBER"},
{"startDate":new Date("1981"),"endDate":new Date("1982"),"taskName":"Beaumont, J.","status":"MEMBER"},
{"startDate":new Date("1982"),"endDate":new Date("1984"),"taskName":"Beaumont, J.","status":"CHAIR"},
{"startDate":new Date("1981"),"endDate":new Date("1984"),"taskName":"Flowerdew, R.","status":"MEMBER"},
{"startDate":new Date("1991"),"endDate":new Date("1994"),"taskName":"Flowerdew, R.","status":"CHAIR"},
{"startDate":new Date("1982"),"endDate":new Date("1984"),"taskName":"Jones, K.","status":"MEMBER"},
{"startDate":new Date("1984"),"endDate":new Date("1985"),"taskName":"Jones, K.","status":"CHAIR"},
{"startDate":new Date("1985"),"endDate":new Date("1986"),"taskName":"Jones, K.","status":"SEC"},
{"startDate":new Date("1988"),"endDate":new Date("1991"),"taskName":"Jones, K.","status":"CHAIR"},
{"startDate":new Date("1991"),"endDate":new Date("2001"),"taskName":"Jones, K.","status":"MEMBER"},
{"startDate":new Date("1982"),"endDate":new Date("1985"),"taskName":"Haining, R.P.","status":"MEMBER"},
{"startDate":new Date("1982"),"endDate":new Date("1985"),"taskName":"Senior,M.","status":"MEMBER"},
{"startDate":new Date("1987"),"endDate":new Date("1993"),"taskName":"Senior,M.","status":"MEMBER"},
{"startDate":new Date("1984"),"endDate":new Date("1987"),"taskName":"Barr,R.","status":"MEMBER"},
{"startDate":new Date("1984"),"endDate":new Date("1985"),"taskName":"Clarke,M.","status":"MEMBER"},
{"startDate":new Date("1985"),"endDate":new Date("1986"),"taskName":"Clarke,M.","status":"CHAIR"},
{"startDate":new Date("1986"),"endDate":new Date("1988"),"taskName":"Clarke,M.","status":"SEC"},
{"startDate":new Date("1984"),"endDate":new Date("1986"),"taskName":"Longley,P.A.","status":"MEMBER"},
{"startDate":new Date("1986"),"endDate":new Date("1988"),"taskName":"Longley,P.A.","status":"CHAIR"},
{"startDate":new Date("1988"),"endDate":new Date("1989"),"taskName":"Longley,P.A.","status":"SEC"},
{"startDate":new Date("1985"),"endDate":new Date("1987"),"taskName":"Clarke, G.","status":"MEMBER"},
{"startDate":new Date("1985"),"endDate":new Date("1987"),"taskName":"Dunn, R.J.","status":"MEMBER"},
{"startDate":new Date("1986"),"endDate":new Date("1987"),"taskName":"Macmillan, W.","status":"MEMBER"},
{"startDate":new Date("1986"),"endDate":new Date("1988"),"taskName":"Lovett, A.","status":"MEMBER"},
{"startDate":new Date("1988"),"endDate":new Date("1991"),"taskName":"Lovett, A.","status":"TRE"},
{"startDate":new Date("1991"),"endDate":new Date("1993"),"taskName":"Lovett, A.","status":"NEWS"},
{"startDate":new Date("1993"),"endDate":new Date("1995"),"taskName":"Lovett, A.","status":"CHAIR"},
{"startDate":new Date("1988"),"endDate":new Date("1989"),"taskName":"Maguire, D.","status":"SECONLY"},
{"startDate":new Date("1991"),"endDate":new Date("1993"),"taskName":"Dunn, C.","status":"MEMBER"},
{"startDate":new Date("1993"),"endDate":new Date("2002"),"taskName":"Dunn, C.","status":"CATMOG"},
{"startDate":new Date("1991"),"endDate":new Date("1996"),"taskName":"Moore, L.","status":"MEMBER"},
{"startDate":new Date("1991"),"endDate":new Date("1993"),"taskName":"Heywood, I.","status":"MEMBER"},
{"startDate":new Date("1993"),"endDate":new Date("1994"),"taskName":"Fisher, P.","status":"MEMBER"},
{"startDate":new Date("1993"),"endDate":new Date("1994"),"taskName":"Martin, D.","status":"NEWS"},
{"startDate":new Date("1994"),"endDate":new Date("1999"),"taskName":"Martin, D.","status":"SEC"},
{"startDate":new Date("1999"),"endDate":new Date("2002"),"taskName":"Martin, D.","status":"CHAIR"},
{"startDate":new Date("1993"),"endDate":new Date("1994"),"taskName":"Gould, M.","status":"POST"},
{"startDate":new Date("1994"),"endDate":new Date("1995"),"taskName":"Gould, M.","status":"MEMBER"},
{"startDate":new Date("1995"),"endDate":new Date("1996"),"taskName":"Gould, M.","status":"NEWS"},
{"startDate":new Date("1994"),"endDate":new Date("1995"),"taskName":"Mitchell, R.","status":"POST"},
{"startDate":new Date("1995"),"endDate":new Date("1996"),"taskName":"Mitchell, R.","status":"MEMBER"},
{"startDate":new Date("1993"),"endDate":new Date("1994"),"taskName":"Higgs, G.","status":"MEMBER"},
{"startDate":new Date("1994"),"endDate":new Date("1995"),"taskName":"Higgs, G.","status":"NEWS"},
{"startDate":new Date("2001"),"endDate":new Date("2005"),"taskName":"Higgs, G.","status":"CHAIR"},
{"startDate":new Date("1994"),"endDate":new Date("1995"),"taskName":"Charlton, M.","status":"MEMBER"},
{"startDate":new Date("1994"),"endDate":new Date("1995"),"taskName":"Langford, I.","status":"MEMBER"},
{"startDate":new Date("1994"),"endDate":new Date("1999"),"taskName":"Fotheringham, S.","status":"CHAIR"},
{"startDate":new Date("1995"),"endDate":new Date("1999"),"taskName":"Bullen, N.","status":"NEWS"},
{"startDate":new Date("1999"),"endDate":new Date("2002"),"taskName":"Bullen, N.","status":"SEC"},
{"startDate":new Date("1999"),"endDate":new Date("2005"),"taskName":"Alvanides, S.","status":"NEWS"},
{"startDate":new Date("2005"),"endDate":new Date("2006"),"taskName":"Alvanides, S.","status":"MEMBER"},
{"startDate":new Date("2000"),"endDate":new Date("2001"),"taskName":"Dorling, D.","status":"MEMBER"},
{"startDate":new Date("1999"),"endDate":new Date("2000"),"taskName":"Atkinson, P.","status":"MEMBER"},
{"startDate":new Date("2000"),"endDate":new Date("2002"),"taskName":"Lloyd, C.","status":"MEMBER"},
{"startDate":new Date("2014"),"endDate":new Date("2015"),"taskName":"Lloyd, C.","status":"CHAIR"},
{"startDate":new Date("1999"),"endDate":new Date("2000"),"taskName":"Anthony, S.","status":"MEMBER"},
{"startDate":new Date("2000"),"endDate":new Date("2002"),"taskName":"Tate, N.","status":"MEMBER"},
{"startDate":new Date("2001"),"endDate":new Date("2002"),"taskName":"Ballas, D.","status":"MEMBER"},
{"startDate":new Date("2001"),"endDate":new Date("2002"),"taskName":"Kalogirou, S.","status":"POST"},
{"startDate":new Date("2005"),"endDate":new Date("2007"),"taskName":"Kalogirou, S.","status":"NEWS"},
{"startDate":new Date("2005"),"endDate":new Date("2007"),"taskName":"Ashby, D.","status":"WEB"},
{"startDate":new Date("2005"),"endDate":new Date("2007"),"taskName":"Harris, R.J.","status":"CHAIR"},
{"startDate":new Date("2005"),"endDate":new Date("2008"),"taskName":"Castle, C.","status":"POST"},
{"startDate":new Date("2005"),"endDate":new Date("2010"),"taskName":"Keylock, C.","status":"MEMBER"},
{"startDate":new Date("2010"),"endDate":new Date("2014"),"taskName":"Keylock, C.","status":"SEC"},
{"startDate":new Date("2005"),"endDate":new Date("2010"),"taskName":"Orford, S.","status":"SEC"},
{"startDate":new Date("2005"),"endDate":new Date("2010"),"taskName":"Orford, S.","status":"SEC"},
{"startDate":new Date("2014"),"endDate":new Date("2015"),"taskName":"Orford, S.","status":"SEC"},
{"startDate":new Date("2005"),"endDate":new Date("2011"),"taskName":"Catney, G.","status":"SEC"},
{"startDate":new Date("2005"),"endDate":new Date("2008"),"taskName":"Singleton, A.","status":"MEMBER"},
{"startDate":new Date("2008"),"endDate":new Date("2012"),"taskName":"Singleton, A.","status":"CHAIR"},
{"startDate":new Date("2008"),"endDate":new Date("2011"),"taskName":"Lewis, D.","status":"POST"},
{"startDate":new Date("2012"),"endDate":new Date("2014"),"taskName":"Lewis, D.","status":"MEMBER"},
{"startDate":new Date("2008"),"endDate":new Date("2015"),"taskName":"Cheshire, J.","status":"MEMBER"},
{"startDate":new Date("2011"),"endDate":new Date("2015"),"taskName":"Morrissey, K.","status":"MEMBER"},
{"startDate":new Date("2012"),"endDate":new Date("2014"),"taskName":"Brunsdon, C.","status":"CHAIR"},
{"startDate":new Date("2012"),"endDate":new Date("2015"),"taskName":"Riddlesden, D.","status":"POST"}
];

var taskStatus = {
    "CHAIR" : "chair",
    "SEC" : "secretary",
    "MEMBER" : "member",
    "CATMOG" : "catmog",
    "TRE" : "treasurer",
    "NEWS" : "news",
    "SECONLY" : "secretary_only",
    "POST" : "postgraduate",
      "WEB" : "website"
};

var taskNames = [ "Robson, B.T.", "Garner, B.J.", "Cowies, S.R.", "Goddard, J.B.","Lewis, P.W.","Cliff, A.","Evans, I.S." ,"Wilson, A.","Taylor, P.","Collins, L.","Hepple, L.","Clark,D.","Unwin,D.","Morgan, R.","Openshaw, S.","Dawson, A.","Johnston, R.","Wrigley, N.","Thrift, N.","Bennett, R.","Ferguson,R.I.","Bradford, M.","Harris, R.","Cox, N.J.","Gattrell, A.C.","Silk, J.","Beaumont, J.","Flowerdew, R.","Jones, K.","Haining, R.P.","Senior,M.","Barr,R.","Clarke,M.","Longley,P.A.","Clarke, G.","Dunn, R.J.","Macmillan, W.","Lovett, A.","Maguire, D.","Dunn, C.","Moore, L.","Heywood, I.","Fisher, P.","Martin, D.","Gould, M.","Mitchell, R.","Higgs, G.","Charlton, M.","Langford, I.","Fotheringham, S.","Bullen, N.","Alvanides, S.","Dorling, D.","Atkinson, P.","Lloyd, C.","Anthony, S.","Tate, N.","Ballas, D.","Kalogirou, S.","Ashby, D.","Harris, R.J.","Harris, R.J.","Keylock, C.","Orford, S.","Catney, G.","Singleton, A.","Lewis, D.","Cheshire, J.","Morrissey, K.","Brunsdon, C.","Riddlesden, D.","Castle, C."];

tasks.sort(function(a, b) {
    return a.endDate - b.endDate;
});
var maxDate = tasks[tasks.length - 1].endDate;
tasks.sort(function(a, b) {
    return a.startDate - b.startDate;
});
var minDate = tasks[0].startDate;

var format = "%Y";

var gantt = d3.gantt().taskTypes(taskNames).taskStatus(taskStatus).tickFormat(format);
gantt(tasks);